name: graph-ml-2
channels:
  - conda-forge
dependencies:
  - fastparquet
  - jupyter
  - kaggle
  - numpy<2
  - omegaconf
  - pandas
  - pip
  - pyarrow
  - pytest
  - python=3.11
  - pytorch
  - pytorch-lightning
  - scikit-learn
  - torchaudio
  - torchmetrics
  - torchvision
  - tqdm
  - wandb
  - pip:
    - PyWavelets==1.9.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.2
    - aiosignal==1.4.0
    - cftime==1.6.5
    - colorlog==6.10.1
    - contourpy==1.3.3
    - cycler==0.12.1
    - docker-pycreds==0.4.0
    - easydev==0.13.3
    - einops==0.8.1
    - fonttools==4.60.1
    - frozenlist==1.8.0
    - kiwisolver==1.4.9
    - lazy_loader==0.4
    - line_profiler==4.2.0
    - lmdb==1.7.5
    - matplotlib==3.10.7
    - mne==1.9.0
    - mne-connectivity==0.7.0
    - multidict==6.7.0
    - netCDF4==1.7.3
    - pooch==1.8.2
    - propcache==0.4.1
    - pyparsing==3.2.5
    - scipy==1.10.1
    - soundfile==0.13.1
    - spectrum==0.9.0
    - torch-geometric==2.7.0
    - torch_cluster==1.6.3
    - torch_scatter==2.1.2
    - torch_sparse==0.6.18
    - torcheeg==1.1.3
    - wfdb==4.1.2
    - xarray==2025.10.1
    - xlrd==2.0.2
    - xmltodict==1.0.2
    - xxhash==3.6.0
    - yarl==1.22.0

